"""
Django settings for sistema_gestao project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-(_0ik-%#-fxf#zc$9ccx!52g2ypwkpzcf*-l)35+mqyae3o4e!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['pi2-stocksystem-backend.onrender.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django_q.apps.DjangoQConfig', # DEVE VIR ANTES do admin para que a tradução funcione
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'rest_framework',
    'django_filters',
    'import_export',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir arquivos estáticos
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.AdminModernizationMiddleware',  # Middleware para modernização do admin
]

ROOT_URLCONF = 'sistema_gestao.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'debug': DEBUG,  # Desabilita cache de templates em desenvolvimento
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ] if DEBUG else [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                ]),
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_gestao.wsgi.application'

X_FRAME_OPTIONS = 'SAMEORIGIN'





# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

USE_I18N = True
LANGUAGE_CODE = 'pt-br'  # Django setting; locale directories should use PT_BR

LANGUAGES = [
    ('pt-br', 'Português (Brasil)'),
    ('en', 'English'),
]

# Project-level and app-level locale lookup
LOCALE_PATHS = [
    BASE_DIR / 'locale',
    BASE_DIR / 'sistema_gestao' / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATICFILES_DIRS = [
    BASE_DIR / "static",
    BASE_DIR / "core" / "static",  # Static files from core app
]
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Configuração do WhiteNoise
# Usando CompressedStaticFilesStorage (sem manifest) para evitar problemas com arquivos não encontrados
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (Arquivos de Upload)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    
    "http://localhost:8080",  # Frontend Vite dev server
    "http://127.0.0.1:8080",
    "http://localhost:3000",  # Alternative React dev server
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Alternative React dev server
    "http://127.0.0.1:5173",
    # Adicione aqui o domínio do seu frontend quando estiver em produção
    # "https://seu-frontend.onrender.com",
    "https://pi2-stock-system.vercel.app",
]

# ADICIONE ESTE BLOCO AQUI PARA O CSRF:
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",  # Alternative React dev server
    "http://127.0.0.1:5173",
    "https://pi2-stock-system.vercel.app",
]
# Para desenvolvimento, permitir qualquer origem (remover em produção)
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_CREDENTIALS = True

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

Q_CLUSTER = {
    'name': 'stock_notifications',
    'workers': 1,  # Número de processos que rodam as tarefas
    'timeout': 180, # Tempo máximo (segundos) que uma tarefa pode rodar (aumentado para 180s)
    'retry': 360,  # Tempo (segundos) para tentar novamente se falhar
    'queue_limit': 50,
    'bulk': 10,
    'orm': 'default', # Usar o banco de dados padrão do Django
}

# Configuração para agendamento de tarefas
# O django_q2 permite criar schedules através do admin ou via código
# Adicione a task check_expiring_products_and_notify no admin em django_q2 > Schedule
# Ou execute o comando: python manage.py qcluster

# --- Configuração de E-mail (Verifique/Ajuste) ---
# Certifique-se de que seu Django está configurado para enviar e-mails.
# Para testes locais, o console backend é o mais fácil:

# MODE: SMTP (Produção) ou CONSOLE (Desenvolvimento)
# Para desenvolvimento (e-mails aparecem no console):
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Para produção (e-mails enviados de verdade):
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # Gmail (ou 'smtp-mail.outlook.com' para Outlook)
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'msbonfim01@gmail.com'
EMAIL_HOST_PASSWORD = 'horo yeqi jysy hfcd'  # Senha de app do Gmail
DEFAULT_FROM_EMAIL = 'msbonfim01@gmail.com'

# Email padrão para envio de notificações (fallback)
# DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@stockystem.com')

# Lista de emails para receber notificações (configure com seus emails)
# NOTIFICATION_EMAILS pode ser configurado via variável de ambiente ou diretamente aqui
notification_emails_env = os.environ.get('NOTIFICATION_EMAILS', '')
if notification_emails_env:
    NOTIFICATION_EMAILS = [email.strip() for email in notification_emails_env.split(',') if email.strip()]
else:
    # Configure aqui seus e-mails para receber notificações
    NOTIFICATION_EMAILS = ['msbonfim01@gmail.com']  # Adicione seus e-mails aqui

# Configurações VAPID para Push Notifications
# Para gerar as chaves VAPID, execute: python gerar_chaves_vapid.py
# Ou use um serviço como OneSignal, Firebase Cloud Messaging

# --- Configuração VAPID para Push Notifications ---
# A chave privada será inserida aqui automaticamente pelo script 'automatizar_chaves.py'.
# Esta abordagem é mais robusta que ler de um arquivo.
# VAPID_PRIVATE_KEY deve ser configurada via variável de ambiente
# NUNCA commite chaves privadas no repositório!
VAPID_PUBLIC_KEY = 'BGvWUBO-xLDlWe8prdXxKWDRi-pLoSvHKJSq1XezDfF_QF4FSIIZGabXanKZdi7I-zIL_CNuyffF3xDnOzOH6iQ'
VAPID_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgvoeErMRVMT4imcQf
5FXLINjUjiyLj3DXiioDsnYuGbihRANCAARr1lATvsSw5VnvKa3V8Slg0YvqS6Er
xyiUqtV3sw3xf0BeBUiCGRmm12pymXYuyPsyC/wjbsn3xd8Q5zszh+ok
-----END PRIVATE KEY-----
"""

VAPID_CLAIMS = {
    "sub": os.environ.get('VAPID_EMAIL', "mailto:admin@stockystem.com")
}