# Generated by Django 4.2.25 on 2026-03-03 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'verbose_name': 'Inscrição de Push', 'verbose_name_plural': 'Inscrições de Push'},
        ),
    ]
